name: "Page Speed Insights"
description: "Utilize Google's Page Speed Insights to audit your application"
branding:
  icon: "cloud-lightning"
  color: "green"
inputs:
  url:
    description: "The URL to run the check against"
  urls:
    description: "The URLs to run the check against"
  threshold:
    description: "Score to pass the PageSpeed test. Useful for setting a performance budget (default 70)."
  strategy:
    description: "Strategy to use when analyzing the page (mobile/desktop)."
  key:
    description: "A PageSpeed Insights API key"
outputs:
  score:
    description: "Performance score of a given URL"
runs:
  using: "node12"
  main: "index.js"
