on: [pull_request]

jobs:
  run_psi:
    runs-on: ubuntu-latest
    name: Running Page Speed Insights
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setting Urls
        run: export $(cat .github/workflows/urls | grep -v ^# | xargs); echo "URLS=$URLS" >> $GITHUB_ENV
      - name: Running Page Speed Insights
        uses: ./ # Uses an action in the root directory
        id: psi
        with:
          urls: ${{ env.URLS }}
          threshold: 85
          strategy: mobile
          key: ${{ secrets.APIKEY }}
      - name: Outputting the performance results of a given URL
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            **PSI performance results: **
            ${{ steps.psi.outputs.score }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false
