on: [pull_request]

jobs:
  run_psi:
    runs-on: ubuntu-latest
    name: Running Page Speed Insights
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Running Page Speed Insights
        uses: ./ # Uses an action in the root directory
        id: psi
        with:
          url: "https://jake.partus.ch"
          threshold: 85
          strategy: mobile
      - name: Outputting the performance results of a given URL
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            **PSI Score: **
            `${{ steps.psi.outputs.score }}`
            **[CoreWebVitals] FCP Score: **
            `${{ steps.psi.outputs.fcp }}`
            **[CoreWebVitals] TTI Score: **
            `${{ steps.psi.outputs.tti }}`
            **[CoreWebVitals] SI Score: **
            `${{ steps.psi.outputs.si }}`
            **[CoreWebVitals] TBT Score: **
            `${{ steps.psi.outputs.tbt }}`
            **[CoreWebVitals] LCP Score: **
            `${{ steps.psi.outputs.lcp }}`
            **[CoreWebVitals] CLS Score: **
            `${{ steps.psi.outputs.cls }}`
            **[CoreWebVitals] FMP Score: **
            `${{ steps.psi.outputs.fmp }}`
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false